name: test

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.4'

      - run: go mod download
      - run: go test ./...